/*
 * This source file was generated by the Gradle 'init' task
 */
package org.kinemine;

import org.kinemine.handler.HelloHandler;
import org.kinemine.handler.UnwatchedMoviesHandler;
import org.kinemine.handler.WatchedMoviesHandler;
import org.kinemine.handler.AllMoviesHandler;
import org.kinemine.handler.TagsHandler;
import org.kinemine.repository.MovieRepository;
import org.kinemine.repository.TagRepository;

import java.net.InetSocketAddress;
import java.nio.file.Path;
import java.nio.file.Paths;

import com.sun.net.httpserver.HttpServer;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        AppConfig.initializeRegistry();
        HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
        Path repositoryPath = Paths.get(System.getenv("REPOSITORY_LOCATION"));

        MovieRepository movieRepo = new MovieRepository(repositoryPath.resolve("movies"));
        TagRepository tagRepo     = new TagRepository(repositoryPath.resolve("tags"));

        server.createContext("/movies/all", new AllMoviesHandler(movieRepo));
        server.createContext("/movies/watched", new WatchedMoviesHandler(movieRepo));
        server.createContext("/movies/unwatched", new UnwatchedMoviesHandler(movieRepo));
        server.createContext("/tags", new TagsHandler(tagRepo));
        server.createContext("/", new HelloHandler());
        server.setExecutor(null);
        server.start();
        System.out.println("Server is listening on port 8080...");
    }

}
